name: Build docker images

on:
  push:
    branches:
      - "feat/refactor"
env: 
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-docker:
    name: Build docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      
      - name: Login in the Github container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/arm/v7

      - name: Docker buildx
        uses: docker/setup-buildx-action@v2