name: Publish in the docker hub

on:
  push:
    branches:
      - "master"

jobs:
  push_to_docker_hub:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
      - uses: actions/checkout@v3
    
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker images
        id: build-and-push-latest
        uses: docker/build-push-action@v3.1.1
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          context: .
          push: true
          tags: isenganime/hexofirebase:latest
          labels: ${{ steps.meta.outputs.label }}